export const INPUT_FIELDS = [
  {
    label: "Course Title:",
    placeholder: "Enter course title",
    key: "courseTitle",
    inputType: "text",
  },
  {
    label: "Course Code:",
    placeholder: "Enter course code",
    key: "courseCode",
    inputType: "text",
  },
  {
    label: "Report Number:",
    placeholder: "Enter report number",
    key: "reportNumber",
    inputType: "number",
  },
  {
    label: "Report Name:",
    placeholder: "Enter report name",
    key: "reportName",
    inputType: "text",
  },
  {
    label: "Date of Solving:    ",
    placeholder: "Enter date of solving",
    key: "dateOfSolving",
    inputType: "date",
  },
  {
    label: "Date of Submission:",
    placeholder: "Enter date of submission",
    key: "dateOfSubmission",
    inputType: "date",
  },
  {
    label: "Name of the Student:",
    placeholder: "Enter name of the student",
    key: "nameOfStudent",
    inputType: "text",
  },
  {
    label: "Student ID:",
    placeholder: "Enter student ID",
    key: "studentID",
    inputType: "text",
  },
  {
    label: "Department:",
    placeholder: "Enter department",
    key: "department",
    inputType: "text",
  },
  {
    label: "Batch:",
    placeholder: "Enter batch",
    key: "batch",
    inputType: "text",
  },
  {
    label: "Semester:",
    placeholder: "Enter semester",
    key: "semester",
    inputType: "text",
  },
  {
    label: "Section:",
    placeholder: "Enter section",
    key: "section",
    inputType: "text",
  },
  {
    label: "Teacher Name:",
    placeholder: "Enter teacher name",
    key: "teacherName",
    inputType: "text",
  },
  {
    label: "Teacher Designation:",
    placeholder: "Enter teacher designation",
    key: "teacherDesignation",
    inputType: "text",
  },
];
